name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Create build script
        run: |
          mkdir -p scripts
          cat > scripts/buildprod.sh << 'EOF'
          #!/bin/bash
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o notely
          EOF
          chmod +x scripts/buildprod.sh
          
      - name: Build application
        run: ./scripts/buildprod.sh